import json
import os
import time
import pandas as pd
from kafka import KafkaProducer

TOPIC = os.getenv("KAFKA_TOPIC", "kdd_stream")
KAFKA_SERVER = os.getenv("KAFKA_SERVER", "localhost:9092")
CSV_PATH = os.getenv("CSV_PATH", "data/kdd_stream.csv")
SLEEP_SECONDS = float(os.getenv("SLEEP_SECONDS", "0.01"))

# For local evaluation keep labels in Kafka messages.
# For production-like simulation run with: SEND_LABEL=false
SEND_LABEL = os.getenv("SEND_LABEL", "true").lower() == "true"

# Optional final shuffle. Keep false if you want the block-wise drift pattern
# generated by train_models.py. Set true for a fully random mixed stream.
SHUFFLE_STREAM = os.getenv("SHUFFLE_STREAM", "false").lower() == "true"
RANDOM_STATE = int(os.getenv("RANDOM_STATE", "42"))


def clean_value(v):
    if pd.isna(v):
        return None
    if hasattr(v, "item"):
        return v.item()
    return v


def main():
    producer = KafkaProducer(
        bootstrap_servers=KAFKA_SERVER,
        value_serializer=lambda v: json.dumps(v).encode("utf-8")
    )

    df = pd.read_csv(CSV_PATH)

    if SHUFFLE_STREAM:
        df = df.sample(frac=1, random_state=RANDOM_STATE).reset_index(drop=True)

    if "label" in df.columns:
        print("Producer stream label distribution:")
        print(df["label"].value_counts(normalize=True).rename(index={0: "normal", 1: "anomaly"}))

    for i, row in df.iterrows():
        record = {k: clean_value(v) for k, v in row.to_dict().items()}
        record["record_id"] = int(i)

        if not SEND_LABEL:
            record.pop("label", None)

        producer.send(TOPIC, record)

        if i % 500 == 0:
            print(f"Sent {i} records")

        time.sleep(SLEEP_SECONDS)

    producer.flush()
    producer.close()
    print("Producer finished.")


if __name__ == "__main__":
    main()